In [123]:
import numpy as np

In [136]:
class Lab5(object):
    def __init__(self):
        self.a = 3
        self.b = 3
        self.init_coefficients = np.zeros((self.a, self.b))
        for i in range(self.a):
            for j in range(self.b):
                print("Введите элеменит {} {}".format(i, j))
                self.init_coefficients[i][j] = float(input())

        self.init_vector = np.zeros(3)
        for i in range(self.b):
            print("Введите свободный член {}".format(i))
            self.init_vector[i] = float(input())
        self.start_vector = self.init_vector.copy()
        self.start_coeff = self.init_coefficients.copy()
        for i in range(self.b):
            self.init_vector[i] /= self.init_coefficients[i][i]
            self.init_coefficients[i] /= self.init_coefficients[i][i]
        self.coefficients = -self.init_coefficients.copy()
        for i in range(self.b):
            self.coefficients[i][i] = 0.
        self.current_step = self.init_vector.copy()
        self.prediction_step = np.zeros(self.b)
        self.epsilon = 0.0002
    
    def calculate_prediction(self):
        for i in range(self.b):
#             print(self.coefficients[i][:i])
            first_step = np.sum(self.coefficients[i][i:] * self.current_step[i:])
#             print(first_step)
            second_step = np.sum(self.coefficients[i][:i] * self.prediction_step[:i])
#             print("pred {}".format(self.prediction_step[:i]))
#             print(second_step)
            self.prediction_step[i] = first_step + second_step + self.init_vector[i]

    
    def solve(self):
        while np.linalg.norm(self.current_step - self.prediction_step) > self.epsilon:
            self.current_step = self.prediction_step.copy()
            self.prediction_step = np.zeros(self.b)
            self.calculate_prediction()
        return self.current_step
    
    def check(self):
        print(self.start_vector)
        print(np.dot(self.start_coeff, self.current_step))

In [137]:
lab5 = Lab5()

Введите элеменит 0 0
10
Введите элеменит 0 1
1
Введите элеменит 0 2
-1
Введите элеменит 1 0
1
Введите элеменит 1 1
10
Введите элеменит 1 2
-1
Введите элеменит 2 0
-1
Введите элеменит 2 1
1
Введите элеменит 2 2
10
Введите свободный член 0
11
Введите свободный член 1
10
Введите свободный член 2
10


In [141]:
lab5.start_coeff

array([[10.,  1., -1.],
       [ 1., 10., -1.],
       [-1.,  1., 10.]])

In [142]:
lab5.start_vector

array([11., 10., 10.])

In [139]:
lab5.solve()

array([1.1021441 , 0.99100869, 1.01111354])

In [140]:
lab5.check()

[11. 10. 10.]
[11.00133615 10.00111746 10.        ]


In [108]:
lab5.coefficients

array([[ 0. , -0.1,  0.1],
       [-0.1,  0. ,  0.1],
       [ 0.1, -0.1,  0. ]])

In [109]:
for i in range(3):
    print(lab5.coefficients[i][:i])

[]
[-0.1]
[ 0.1 -0.1]


In [110]:
lab5.init_vector

array([1.1, 1. , 1. ])

In [111]:
lab5.init_coefficients[2][0:]

array([-0.1,  0.1,  1. ])

In [113]:
print(lab5.current_step)

[1.1   0.99  1.011]


In [115]:
lab5.calculate_prediction()
print(lab5.current_step)

[]
0.002023099999999986
pred []
0.0
[-0.1]
0.1011121
pred [1.1020231]
-0.11020231000000001
[ 0.1 -0.1]
0.0
pred [1.1020231  0.99090979]
0.011111331000000002
[1.1020231  0.99090979 1.01111133]


In [124]:
lab5.init_coefficients

array([[ 1. ,  0.1, -0.1],
       [ 0.1,  1. , -0.1],
       [-0.1,  0.1,  1. ]])

In [126]:
for i in range(3):
    if i-1 >= 0:
        print(lab5.init_coefficients[i][:i])

[0.1]
[-0.1  0.1]


In [10]:
j

1