In [3]:
import numpy as np

In [24]:
class Lab5(object):
    def __init__(self):
        self.a = 3
        self.b = 3
        self.init_coefficients = np.zeros((self.a, self.b))
        for i in range(self.a):
            for j in range(self.b):
                print("Введите элеменит {} {}".format(i, j))
                self.init_coefficients[i][j] = float(input())

        self.init_vector = np.zeros(3)
        for i in range(self.b):
            print("Введите свободный член {}".format(i))
            self.init_vector[i] = float(input())
        self.start_vector = self.init_vector.copy()
        self.start_coeff = self.init_coefficients.copy()
        for i in range(self.b):
            self.init_vector[i] /= self.init_coefficients[i][i]
            self.init_coefficients[i] /= self.init_coefficients[i][i]
        self.coefficients = -self.init_coefficients.copy()
        for i in range(self.b):
            self.coefficients[i][i] = 0.
        self.current_step = self.init_vector.copy()
        self.prediction_step = np.zeros(self.b)
        self.epsilon = 0.0002
    
    def calculate_prediction(self):
        for i in range(self.b):
#             print(self.coefficients[i][:i])
            first_step = np.sum(self.coefficients[i][i:] * self.current_step[i:])
#             print(first_step)
            second_step = np.sum(self.coefficients[i][:i] * self.prediction_step[:i])
#             print("pred {}".format(self.prediction_step[:i]))
#             print(second_step)
            self.prediction_step[i] = first_step + second_step + self.init_vector[i]

    
    def solve(self):
        while np.linalg.norm(self.current_step - self.prediction_step) > self.epsilon:
            self.current_step = self.prediction_step.copy()
            self.prediction_step = np.zeros(self.b)
            self.calculate_prediction()
        return self.current_step
    
    def check(self):
        print("Проверка")
        print("Исходный вектор свободных членов {}".format(self.start_vector))
        print("Подстановка решения {}".format(np.dot(self.start_coeff, self.current_step)))

In [25]:
lab5 = Lab5()

Введите элеменит 0 0
10
Введите элеменит 0 1
1
Введите элеменит 0 2
-1
Введите элеменит 1 0
1
Введите элеменит 1 1
10
Введите элеменит 1 2
-1
Введите элеменит 2 0
-1
Введите элеменит 2 1
1
Введите элеменит 2 2
10
Введите свободный член 0
11
Введите свободный член 1
10
Введите свободный член 2
10


In [26]:
print("Исходные коэффициенты системы \n {}".format(lab5.start_coeff))

Исходные коэффициенты системы 
 [[10.  1. -1.]
 [ 1. 10. -1.]
 [-1.  1. 10.]]


In [27]:
print("Исохдный вектор свободных членов \n {}".format(lab5.start_vector))

Исохдный вектор свободных членов 
 [11. 10. 10.]


In [28]:
print("Решение системы \n {}".format(lab5.solve()))

Решение системы 
 [1.1021441  0.99100869 1.01111354]


In [29]:
lab5.check()

Проверка
Исходный вектор свободных членов [11. 10. 10.]
Подстановка решения [11.00133615 10.00111746 10.        ]
