In [1]:
import numpy as np

In [59]:
class Lab3(object):
    def __init__(self, number_of_equations=3):
        self.number_of_equations = number_of_equations
        self.matrix_of_coefficients = np.zeros((self.number_of_equations, number_of_equations))
        for i in range(number_of_equations):
            for j in range(number_of_equations):
                print("Введите коэффициент {} {}".format(i, j))
                self.matrix_of_coefficients[i, j] = float(input())
        self.vector_of_values = np.zeros(3)
        self.init_matrix = self.matrix_of_coefficients.copy()
        for i in range(number_of_equations):
            print("Введите свободный член {}".format(i))
            self.vector_of_values[i] = float(input())
        self.init_value = self.vector_of_values.copy()
        self.solution = np.zeros(3)
        
    def get_triangular_matrix(self):
        print(self.matrix_of_coefficients)
        for i in range(0, self.number_of_equations - 1):
            for j in range(i, self.number_of_equations-1):
                k = self.matrix_of_coefficients[j+1, i] / self.matrix_of_coefficients[i, i]
                self.matrix_of_coefficients[j+1, :] -= self.matrix_of_coefficients[i, :] * k
                                                        
                self.vector_of_values[j+1] -= self.vector_of_values[i] * k
            print(self.matrix_of_coefficients)
    
    def solve_eqution(self):
        self.get_triangular_matrix()
        x3 = self.vector_of_values[2] / self.matrix_of_coefficients[2, 2]
        x2 = (self.vector_of_values[1] - self.matrix_of_coefficients[1, 2]*x3) / self.matrix_of_coefficients[1, 1]
        x1 = (self.vector_of_values[0] - x2 * self.matrix_of_coefficients[0,1] - x3 * self.matrix_of_coefficients[0, 2]) / self.matrix_of_coefficients[0][0]
        print("Решение СЛАУ:\nx1={}\nx2={}\nx3={}".format(x1, x2, x3))
        self.solution = np.array([x1, x2, x3])
    
    def check(self):
        print("Вектор свободных членов {}".format(self.init_value))
        first_eqution_value = np.sum(self.init_matrix[0, :] * self.solution)
        print("Первое уравнение подстановка значение {}".format(first_eqution_value))
        second_eqution_value = np.sum(self.init_matrix[1, :] * self.solution)
        print("Второе уравнение подстановка значение {}".format(second_eqution_value))
        third_eqution_value = np.sum(self.init_matrix[2, :] * self.solution)
        print("Третье уравнение подстановка значение {}".format(third_eqution_value))

In [60]:
solve = Lab3()

Введите коэффициент 0 0
5
Введите коэффициент 0 1
6
Введите коэффициент 0 2
7
Введите коэффициент 1 0
2
Введите коэффициент 1 1
8
Введите коэффициент 1 2
3
Введите коэффициент 2 0
7
Введите коэффициент 2 1
5
Введите коэффициент 2 2
7
Введите свободный член 0
8
Введите свободный член 1
2
Введите свободный член 2
8


In [61]:
solve.solve_eqution()

[[5. 6. 7.]
 [2. 8. 3.]
 [7. 5. 7.]]
[[ 5.   6.   7. ]
 [ 0.   5.6  0.2]
 [ 0.  -3.4 -2.8]]
[[ 5.00000000e+00  6.00000000e+00  7.00000000e+00]
 [ 0.00000000e+00  5.60000000e+00  2.00000000e-01]
 [ 0.00000000e+00 -4.44089210e-16 -2.67857143e+00]]
Решение СЛАУ:
x1=-0.133333333333
x2=-0.266666666667
x3=1.46666666667


In [62]:
solve.check()

Вектор свободных членов [8. 2. 8.]
Первое уравнение подстановка значение 8.0
Второе уравнение подстановка значение 2.0
Третье уравнение подстановка значение 8.0
