In [3]:
import numpy as np

In [12]:
class Lab3(object):
    def __init__(self, number_of_equations=3):
        self.number_of_equations = number_of_equations
        self.matrix_of_coefficients = np.zeros((self.number_of_equations, number_of_equations))
        for i in range(number_of_equations):
            for j in range(number_of_equations):
                print("Введите коэффициент {} {}".format(i, j))
                self.matrix_of_coefficients[i, j] = float(input())
        self.vector_of_values = np.zeros(3)
        self.init_matrix = self.matrix_of_coefficients.copy()
        for i in range(number_of_equations):
            print("Введите свободный член {}".format(i))
            self.vector_of_values[i] = float(input())
        self.init_value = self.vector_of_values.copy()
        self.solution = np.zeros(3)
        
    def get_triangular_matrix(self):
        print(self.matrix_of_coefficients)
        for i in range(0, self.number_of_equations - 1):
            for j in range(i, self.number_of_equations-1):
                k = self.matrix_of_coefficients[j+1, i] / self.matrix_of_coefficients[i, i]
                self.matrix_of_coefficients[j+1, :] -= self.matrix_of_coefficients[i, :] * k
                                                        
                self.vector_of_values[j+1] -= self.vector_of_values[i] * k
            l = self.matrix_of_coefficients[i][i] 
            self.matrix_of_coefficients[i, :] /= l
            self.vector_of_values[i] /= l
        l = self.matrix_of_coefficients[2][2] 
        self.matrix_of_coefficients[2, :] /= l
        self.vector_of_values[2] /= l
        print(self.matrix_of_coefficients)

    
    def solve_eqution(self):
        self.get_triangular_matrix()
        x3 = self.vector_of_values[2]
        x2 = (self.vector_of_values[1] - self.matrix_of_coefficients[1, 2]*x3)
        x1 = (self.vector_of_values[0] - x2 * self.matrix_of_coefficients[0,1] - x3 * self.matrix_of_coefficients[0, 2])
        print("Решение СЛАУ:\nx1={}\nx2={}\nx3={}".format(x1, x2, x3))
        self.solution = np.array([x1, x2, x3])
    
    def check(self):
        print("Вектор свободных членов {}".format(self.init_value))
        first_eqution_value = np.sum(self.init_matrix[0, :] * self.solution)
        print("Первое уравнение подстановка значение {}".format(first_eqution_value))
        second_eqution_value = np.sum(self.init_matrix[1, :] * self.solution)
        print("Второе уравнение подстановка значение {}".format(second_eqution_value))
        third_eqution_value = np.sum(self.init_matrix[2, :] * self.solution)
        print("Третье уравнение подстановка значение {}".format(third_eqution_value))

In [16]:
solve = Lab3()

Введите коэффициент 0 0
5
Введите коэффициент 0 1
-3
Введите коэффициент 0 2
2
Введите коэффициент 1 0
2
Введите коэффициент 1 1
6
Введите коэффициент 1 2
3
Введите коэффициент 2 0
3
Введите коэффициент 2 1
-2
Введите коэффициент 2 2
7
Введите свободный член 0
19
Введите свободный член 1
7
Введите свободный член 2
29


In [17]:
solve.solve_eqution()

[[ 5. -3.  2.]
 [ 2.  6.  3.]
 [ 3. -2.  7.]]
[[ 1.         -0.6         0.4       ]
 [ 0.          1.          0.30555556]
 [ 0.          0.          1.        ]]
Решение СЛАУ:
x1=2.0
x2=-1.0
x3=3.0


In [18]:
solve.check()

Вектор свободных членов [19.  7. 29.]
Первое уравнение подстановка значение 19.0
Второе уравнение подстановка значение 7.0
Третье уравнение подстановка значение 29.0
